### ISSUE TITLE
Icon sizes are wrong in cf-component-icon

### ISSUE THREAD

**Issue by thellimist** [cloudflare/cf-ui#260]
https://cloudflare.github.io/cf-ui/#cf-component-icon

![](https://image.prntscr.com/image/wF0pTn8kQn2B6usOY3yNQA.png)

**Comment by koddsson** [comment]
I can get this fixed in #199 although I'm trying to push that each implementation should overwrite the `font-size` property itself for fine-grained size controls.

**Comment by jwineman** [comment]
@thellimist is this from partners? All of our components are still pre-fela so even if this gets fixed we won't get it until we upgrade.

**Comment by wyuenho** [comment]
The sizes are not wrong. The icons are not meant to be looked at as an entire set like your regular fonts, so if some glyph seems drastically smaller, that's because you are comparing it to the bigger ones. We could get the designers to give us an entirely new set of icons, but they are probably still not going to look all the same size. Icons only need to look consistent to the surrounding contexts.

**Comment by koddsson** [comment]
@wyuenho I'm not sure I follow. How are the icons sizes not wrong when they are all the same size?

**Comment by koddsson** [comment]
This is blocked while #199 is blocked. Will revisit when that one is merged/closed.

**Comment by toekneestuck** [comment]
Moved internal.
